fix #1: add playwright end to end tests that run in docker
radiasoft/container-sirepo-e2e pull request #2
Opened 2022-11-18 23:24 UTC by garsuga

2022-11-18 23:26 UTC, garsuga commented
This will fix https://github.com/radiasoft/sirepo/issues/4488 and https://github.com/radiasoft/sirepo/issues/5111

2022-11-19 18:31 UTC, robnagler commented
@garsuga is this ready for review, I think there's an issue with [the link code](https://github.com/radiasoft/container-sirepo-e2e/pull/2/files#diff-54e0e0c350478e907d296f190eaaf2b28793a59e67651687eea83bc0493eca97R168). The variable `link` doesn't exist for the `page.goto`.

2022-11-21 22:53 UTC, garsuga commented
Yes, sorry, that was the line I removed while you were looking over it with me and I forgot to replace it. I have fixed and tested it now

2022-11-22 20:33 UTC, robnagler requested changes
I'm getting this error:

```txt
 1) srw/simulation-functions.spec.js:4:1 › SRW Login With Email ===================================

    locator.click: Error: strict mode violation: locator('button').filter({ has: locator('text=/^\\s*Submit\\s*$/') }) resolved to 2 elements:
        1) <button class="btn btn-primary" data-ng-click="loginConf…>Submit</button> aka getByRole('button', { name: 'Submit' })
        2) <button disabled="disabled" class="btn btn-primary" data…>Submit</button> aka locator('#sbatch-login-modal').getByText('Submit')

    =========================== logs ===========================
    waiting for locator('button').filter({ has: locator('text=/^\\s*Submit\\s*$/') })
      strict mode violation: locator('button').filter({ has: locator('text=/^\\s*Submit\\s*$/') }) resolved to 2 elements:
        1) <button class="btn btn-primary" data-ng-click="loginConf…>Submit</button> aka getByRole('button', { name: 'Submit' })
        2) <button disabled="disabled" class="btn btn-primary" data…>Submit</button> aka locator('#sbatch-login-modal').getByText('Submit')

    ============================================================

       at testing-utils.js:185

      183 |         await page.locator("input[name=displayName]").type("Test"); // TODO unique name
      184 |         await page.waitForTimeout(250);
    > 185 |         await page.locator("button", { has: page.locator(textFuzzyEquals("Submit")) }).click();
          |                                                                                        ^
      186 |     }
      187 |     await page.waitForURL(`${HOST}/${applicationName}#/simulations`)
      188 | }

        at loginWithEmail (/home/vagrant/playwright/tests/testing-utils.js:185:88)
        at loginIfNeeded (/home/vagrant/playwright/tests/testing-utils.js:147:9)
        at /home/vagrant/playwright/tests/srw/simulation-functions.spec.js:6:5
```

2022-11-22 20:33 UTC, robnagler commented on README.md
> +`docker run --rm -it --network=host -v $HOME/mail:$HOME/mail <CONTAINER>`
Maybe use a fence so easier to copy-and-paste and make easier to use:

```sh
docker run --rm -it --network=host -v $HOME/mail:$HOME/mail radiasoft/sirepo-e2e bash -l -c 'cd ~/playwright && npx playwright test'
```

`bash -l` is necessary to run ~/.bashrc which includes the post_bivio_bashrc. Give the command on one line let's people copy and paste it. Eventually, we'll add a default command, but for now, this is better.

2022-11-22 20:33 UTC, robnagler commented on container-conf/playwright/tests/testing-utils.js
> +export let textMatch = (pattern) => {
I don't this is a useful way to program regular expressions. textFuzzyEquals doesn't really tell me what I want to know. I would think of textFuzzy would mean something like soundex, not simply ignoring white space.

Rather, this is a contentRe(), because it is something very specific, and you don't really want these functions used elsewhere under the principle of [Publish as little as you can as late as you can](https://martinfowler.com/ieeeSoftware/published.pdf). 

Also on regexes for testing, you probably want to ignore case as that makes the test less rigid using the [Robustness Principle](https://en.wikipedia.org/wiki/Robustness_principle). You also might want to ignore extra whitespace in between and ensure metachars match properly, e.g. 

```js
let t = text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replace(/\s+/, "\\s+");
return `/^\s*${pattern}\s*$/is`;
```

There's a function for regex meta character escaping, and there is a proposal for it to be added to ES, it's not there so I recommend a little copying better than another dependency. You could argue escape should be its own function. :)

2022-11-22 20:33 UTC, robnagler commented on README.md
> +# container-sirepo-e2e
Give a bit more context, e.g. to start sirepo, do bash etc/run-auth-moderate.sh and to make sure you are using port 8000.

2022-11-22 20:33 UTC, robnagler commented on container-conf/playwright/tests/testing-utils.js
> +let HOST_BASE = "localhost:8000"
How does playwright support configuration? This should be configurable but default to localhost:8000. It would be simpler if this were just:

```js
let HOME_PAGE = "http://localhost:8000"
```

The extra names imply these things are used elsewhere and aren't. Ideally, you'd just supply a URI as a single configuration parameter.

2022-11-22 20:33 UTC, robnagler commented on container-conf/playwright/tests/testing-utils.js
> +        this.linkPattern = /^\s*(http.+?auth-email-authorized.+?)\s*$/gm;
I think this is a better regexp matcher:

```js
/https?:\/\/[^\/\s]+\/auth-email-authorized\/\w+\/\w+/i
```

There's no need to match multiple (that decision should be deferred to where it is used), and we just want to match the first expression. It needed be on its own line. While this is more rigid in some ways, it allows us to find something we know about (how the uri is constructed). This allows us to be more flexible in the areas that need to be (formatting of the email message), since we know that the URI has to be properly constructed for it to work.

The word "Link" is imprecise. I think URI or URL is better.

2022-11-22 20:33 UTC, robnagler commented on container-conf/playwright/tests/testing-utils.js
> +    getFullPath = (mailFile) => {
Traditionally called absPath or absolutePath.

2022-11-22 20:33 UTC, robnagler commented on container-conf/playwright/tests/testing-utils.js
> +            throw new Error(`found multiple (${matches.length}) matches for signin link in email '${mailString}'`);
This is not going to be an error. There may be reasons to include the link multiple times in a text going to users especially in this kind of message. The test doesn't want to test all links (that's not likely to break) nor does it care about whether it is repeated.

2022-11-22 20:33 UTC, robnagler commented on container-conf/playwright/tests/testing-utils.js
> +            throw new Error("could not find signin link in email '" + mailString + "'");
mailstring could be long so don't include quotes. Rather, just `signin link not found in email: ${mailString}`.

2022-11-22 20:33 UTC, robnagler commented on container-conf/playwright/tests/testing-utils.js
> +        let fileNames = fs.readdirSync(this.mailPath);
Temporary unnecessary

2022-11-22 20:33 UTC, robnagler commented on container-conf/playwright/tests/testing-utils.js
> +    mailManager.deleteAllEmails();
In testing, it's convenient to not delete test output unless necessary. In this case, you are deleting the files on entry, and just leave them there in the case the test fails.

2022-11-22 20:33 UTC, robnagler commented on container-conf/playwright/tests/testing-utils.js
> +    if(NEEDS_EMAIL_LOGIN) {
We put a space after `if`.

2022-11-22 20:33 UTC, robnagler commented on container-conf/playwright/tests/testing-utils.js
> +    } else {
We use:

```js
}
else {
```

2022-11-22 20:33 UTC, robnagler commented on container-conf/playwright/tests/testing-utils.js
> +    } catch {
```js
}
catch {
```

2022-11-22 20:33 UTC, robnagler commented on container-conf/playwright/tests/testing-utils.js
> +    return new Promise((resolve, reject) => {
I think reject should fail in tests by default. In this case, errors are ignored.

2022-11-22 20:33 UTC, robnagler commented on container-conf/playwright/tests/testing-utils.js
> +    await page.goto(HOST + "/" + applicationName);
application => app.

2022-11-22 20:33 UTC, robnagler commented on container-conf/playwright/tests/testing-utils.js
> +        if(mailPath === "/" || mailPath.length == 0) {
Test for writable and a directory: fs.accessSync and fs.statSync.

2022-11-22 20:33 UTC, robnagler commented on container-conf/playwright/tests/testing-utils.js
> +                        reject(new Error("did not detect a mail file in time"));
remove "mail" and instead include mail directory in error message.

2022-11-22 20:33 UTC, robnagler commented on container-conf/playwright/tests/testing-utils.js
> +        for(let mailFile of this.listMail()) {
This didn't work on my server. All files were there.

2022-11-22 20:33 UTC, robnagler commented on container-conf/playwright/tests/testing-utils.js
> +        downloadCausePromise
Our style is comma terminator for list elements so that you don't get errors not including the comma on the previous line.

2022-11-22 20:33 UTC, robnagler commented on container-conf/playwright/tests/testing-utils.js
> +        let firstItemLocator = page.locator(".sr-icon-col div.sr-thumbnail", { has: page.locator("span.glyphicon") }).first();
I find the names too long. Naming a variable elementHandle which is only used on the next line means I have to think about about "what is elementHandle?" If it is x or something like that, it's just a temporary, and the name is uninteresting.

2022-11-22 20:33 UTC, robnagler commented on container-conf/playwright/tests/testing-utils.js
> +    console.log(link);
Wrap console.log or remove them.

2022-11-28 22:55 UTC, garsuga commented
Which environment are you getting that error on? Just the standard development version using run-auth-moderate?

2022-11-28 23:50 UTC, robnagler commented
Correct. Running e2e in docker against master run-auth-moderate.sh

2022-12-12 19:41 UTC, garsuga commented on container-conf/playwright/tests/testing-utils.js
> +    return new Promise((resolve, reject) => {
Unhandled rejects in JS become errors and errors in Playwright will fail the test and give the reason as the error itself.

2022-12-12 19:50 UTC, garsuga commented on container-conf/playwright/tests/testing-utils.js
> +        for(let mailFile of this.listMail()) {
Was this running in Docker?

2023-01-09 18:27 UTC, garsuga commented
Got it tested and it seems to be working now. Used run-auth-moderate.sh without adding srw to the moderation sim types. Tried to make another script but I kept encountering errors sending emails. Can you try the tests again?

2023-01-09 20:17 UTC, robnagler requested changes
- It would be great if npx had a config that set color to false so the output isn't goofy. 
- I'm getting a failure, but I suspect it is due to https://github.com/radiasoft/sirepo/issues/5342, but not sure since srw is not a react app
```
^[[2A^[[2K^[[0G  ✘  2 srw/simulation-functions.spec.js:10:1 › SRW Discard Changes To Example (30s)^[[2E

  1) srw/simulation-functions.spec.js:10:1 › SRW Discard Changes To Example ========================

    ^[[31mTest timeout of 30000ms exceeded.^[[39m

    locator.elementHandle: Target closed
    =========================== logs ===========================
    waiting for locator('.sr-icon-col div.sr-thumbnail').filter({ has: locator('span.glyphicon') }).first()
    ============================================================

       at testing-utils.js:196

      194 |         console.log("entering next item");
      195 |         let firstItemLocator = page.locator(".sr-icon-col div.sr-thumbnail", { has: page.locator("span.glyphicon") }).first();
    > 196 |         let isFolder = await (await firstItemLocator.elementHandle()).$eval("span.glyphicon", (node) => node.classList.contains("glyphicon-folder-close\
"));
          |                                                      ^
      197 |         await firstItemLocator.first().dblclick();
      198 |         await page.waitForTimeout(250);
      199 |         if (isFolder) {

        at enterNextItem (/home/vagrant/playwright/tests/testing-utils.js:196:54)
        at navigateToFirstSimulation (/home/vagrant/playwright/tests/testing-utils.js:204:11)
        at /home/vagrant/playwright/tests/srw/simulation-functions.spec.js:15:11

    Pending operations:
      - locator.elementHandle at tests/testing-utils.js:196:54
```

2023-01-09 22:24 UTC, garsuga commented
Had no luck finding color configs for npx (and npm did not have them in the past) but the error you have is the same I ran into when moderation was turned on for SRW.

2023-01-09 22:43 UTC, robnagler commented
Try to set $NO_COLOR. https://docs.npmjs.com/cli/v9/using-npm/config#color

I think moderation testing should work. Do you understand the error?

2023-01-09 22:46 UTC, garsuga commented
After login (since we test SRW) we are redirected to a moderation request page rather than the application home page.

2023-01-09 22:46 UTC, garsuga commented
Running `NO_COLOR=1 npx playwright test` seems to have no effect on colors.

2023-01-09 22:47 UTC, garsuga commented
I am not sure if NPM can control the colors output by NPX, Playwright, or React.

2023-01-09 22:51 UTC, robnagler commented
This seems to work:

```txt
 docker run --rm -i --network=host -v $HOME/mail:$HOME/mail radiasoft/sirepo-e2e bash -l -c 'cd ~/playwright && npx playwright test'

Running 2 tests using 1 worker

  ✓  1 srw/simulation-functions.spec.js:4:1 › SRW Login With Email (4s)
entering next item
```

By running without a tty on docker, it doesn't output color.

2023-01-10 18:29 UTC, garsuga commented on container-conf/playwright/tests/testing-utils.js
> +export let textMatch = (pattern) => {
I'm not sure I understand all of what is being said here. Should this function be used as a wrapper around other regex or in a different way?

2023-01-10 18:57 UTC, robnagler commented on container-conf/playwright/tests/testing-utils.js
> +export let textMatch = (pattern) => {
Rewrite textFuzzyEquals to contentRe like this:

```js
let contentRe = (text) => {
    let t = text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replace(/\s+/, "\\s+");
    return `/^\s*${t}\s*$/is`;
}
```

2023-01-10 21:01 UTC, garsuga commented on container-conf/playwright/tests/testing-utils.js
> +export let textMatch = (pattern) => {
That regex does not seem to match the text that is intended. I have renamed the old function to make more sense for now

2023-01-10 21:21 UTC, robnagler commented on container-conf/playwright/tests/testing-utils.js
> +export let textMatch = (pattern) => {
what happens?

2023-01-10 21:31 UTC, garsuga commented on container-conf/playwright/tests/testing-utils.js
> +export let textMatch = (pattern) => {
I fixed the issue I think. Needed some escapes and some playwright stuff wrapping it.

2023-01-11 20:21 UTC, garsuga commented
@robnagler are there other changes that are still requested or can this PR be merged?

2023-01-12 01:05 UTC, robnagler commented
Do all tests pass now?

2023-01-12 21:30 UTC, garsuga commented
Yes it passes the two tests that are defined.

2023-01-13 00:30 UTC, robnagler approved these changes

2023-01-13 00:30 UTC, merged